name: warranty_watch
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 2.1.0
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: 1.0.3
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.13
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.3.7
  image_picker: ^0.8.4+9
  intl: ^0.17.0
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  firebase_analytics: ^9.1.0
  cached_network_image: ^3.2.0
  firebase: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  freezed: ^1.1.1
  flutter_native_splash: ^2.0.4
flutter:
  assets: 
  - assets/
  uses-material-design: true
flutter_native_splash:
  color: '#141414'
  image: assets/app_icon.png
  web: false
